server:
  port: 8081

spring:
  profiles:
    include:
      - domain

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      authentication-database: admin
      database: apiservice
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

  kafka:
    topic-name: excelparser
    bootstrap-servers:
      - ${KAFKA_HOST}:9092
    consumer:
      group-id: api
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.jhsfully.domain.kafkamodel.ExcelParserModel'
      isolation-level: read_committed
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate