spring:
  profiles:
    include:
      - domain
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  payment:
      kakao:
        request-url: https://kapi.kakao.com/v1/payment/ready
        approve-url: https://kapi.kakao.com/v1/payment/approve
        success-url: http://localhost:3000/payment/redirect/success
        refund-url: https://kapi.kakao.com/v1/payment/cancel
        fail-url: http://localhost:3000/grade-payment
        cancel-url: http://localhost:3000/grade-payment
        cid: TC0ONETIME
        admin-key: ${KAKAO_ADMIN_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email,
            client-name: kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      authentication-database: admin
      database: apiservice
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

  kafka:
    topic-name: excelparser
    bootstrap-servers:
      - ${KAFKA_HOST}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jwt:
    secret: ENTER YOUR JWT SECRET KEY

  excel-storage-path: ${EXCEL_STORAGE_PATH}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always