spring:
  profiles:
    include:
      - domain
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  payment:
      kakao:
        request-url: https://kapi.kakao.com/v1/payment/ready
        approve-url: https://kapi.kakao.com/v1/payment/approve
        success-url: http://localhost:8080/payment/redirect/success
        refund-url: https://kapi.kakao.com/v1/payment/cancel
        fail-url: http://localhost:8080
        cancel-url: http://localhost:8080
        cid: TC0ONETIME
        admin-key: ${KAKAO_ADMIN_KEY}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,account_email
            client-name: kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  data:

    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: apiservice
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

#    elasticsearch:
#      cluster-names: apiinfo
#      cluster-node: localhost:9200

  elasticsearch:
    server: localhost:9200

  kafka:
    topic-name: excelparser
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jwt:
    secret: ENTER YOUR JWT SECRET KEY

  excel-storage-path: ${EXCEL_STORAGE_PATH}