spring:
  profiles:
    include:
      - domain

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      authentication-database: admin
      database: apiservice
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}